PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户信息模块
    url(r'^StationInfo/', include('apps.StationInfo.urls', namespace='StationInfo')),  # 机场信息模块
    url(r'^Flight/', include('apps.Flight.urls', namespace='Flight')),  # 航班信息模块
    url(r'^SeatType/', include('apps.SeatType.urls', namespace='SeatType')),  # 座位席别模块
    url(r'^OrderInfo/', include('apps.OrderInfo.urls', namespace='OrderInfo')),  # 订单信息模块
    url(r'^Recharge/', include('apps.Recharge.urls', namespace='Recharge')),  # 充值信息模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/StationInfo/urls.py
from apps.StationInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'StationInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<stationId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<stationId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<stationId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<stationId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/StationInfo/models.py
from django.db import models


class StationInfo(models.Model):
    stationId = models.AutoField(primary_key=True, verbose_name='记录编号')
    stationName = models.CharField(max_length=20, default='', verbose_name='机场名称')
    connectPerson = models.CharField(max_length=20, default='', verbose_name='联系人')
    telephone = models.CharField(max_length=30, default='', verbose_name='联系电话')
    postcode = models.CharField(max_length=20, default='', verbose_name='邮编')
    address = models.CharField(max_length=20, default='', verbose_name='通讯地址')

    class Meta:
        db_table = 't_StationInfo'
        verbose_name = '机场信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        stationInfo = {
            'stationId': self.stationId,
            'stationName': self.stationName,
            'connectPerson': self.connectPerson,
            'telephone': self.telephone,
            'postcode': self.postcode,
            'address': self.address,
        }
        return stationInfo


PythonProject/apps/StationInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.StationInfo.models import StationInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台机场信息添加
    def get(self,request):

        # 使用模板
        return render(request, 'StationInfo/stationInfo_frontAdd.html')

    def post(self, request):
        stationInfo = StationInfo() # 新建一个机场信息对象然后获取参数
        stationInfo.stationName = request.POST.get('stationInfo.stationName')
        stationInfo.connectPerson = request.POST.get('stationInfo.connectPerson')
        stationInfo.telephone = request.POST.get('stationInfo.telephone')
        stationInfo.postcode = request.POST.get('stationInfo.postcode')
        stationInfo.address = request.POST.get('stationInfo.address')
        stationInfo.save() # 保存机场信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改机场信息
    def get(self, request, stationId):
        context = {'stationId': stationId}
        return render(request, 'StationInfo/stationInfo_frontModify.html', context)


class FrontListView(BaseView):  # 前台机场信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        stationName = self.getStrParam(request, 'stationName')
        connectPerson = self.getStrParam(request, 'connectPerson')
        telephone = self.getStrParam(request, 'telephone')
        postcode = self.getStrParam(request, 'postcode')
        # 然后条件组合查询过滤
        stationInfos = StationInfo.objects.all()
        if stationName != '':
            stationInfos = stationInfos.filter(stationName__contains=stationName)
        if connectPerson != '':
            stationInfos = stationInfos.filter(connectPerson__contains=connectPerson)
        if telephone != '':
            stationInfos = stationInfos.filter(telephone__contains=telephone)
        if postcode != '':
            stationInfos = stationInfos.filter(postcode__contains=postcode)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(stationInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        stationInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'stationInfos_page': stationInfos_page,
            'stationName': stationName,
            'connectPerson': connectPerson,
            'telephone': telephone,
            'postcode': postcode,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'StationInfo/stationInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示机场信息详情页
    def get(self, request, stationId):
        # 查询需要显示的机场信息对象
        stationInfo = StationInfo.objects.get(stationId=stationId)
        context = {
            'stationInfo': stationInfo
        }
        # 渲染模板显示
        return render(request, 'StationInfo/stationInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有机场信息
    def get(self,request):
        stationInfos = StationInfo.objects.all()
        stationInfoList = []
        for stationInfo in stationInfos:
            stationInfoObj = {
                'stationId': stationInfo.stationId,
                'stationName': stationInfo.stationName,
            }
            stationInfoList.append(stationInfoObj)
        return JsonResponse(stationInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式机场信息更新
    def get(self, request, stationId):
        # GET方式请求查询机场信息对象并返回机场信息json格式
        stationInfo = StationInfo.objects.get(stationId=stationId)
        return JsonResponse(stationInfo.getJsonObj())

    def post(self, request, stationId):
        # POST方式提交机场信息修改信息更新到数据库
        stationInfo = StationInfo.objects.get(stationId=stationId)
        stationInfo.stationName = request.POST.get('stationInfo.stationName')
        stationInfo.connectPerson = request.POST.get('stationInfo.connectPerson')
        stationInfo.telephone = request.POST.get('stationInfo.telephone')
        stationInfo.postcode = request.POST.get('stationInfo.postcode')
        stationInfo.address = request.POST.get('stationInfo.address')
        stationInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台机场信息添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'StationInfo/stationInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        stationInfo = StationInfo() # 新建一个机场信息对象然后获取参数
        stationInfo.stationName = request.POST.get('stationInfo.stationName')
        stationInfo.connectPerson = request.POST.get('stationInfo.connectPerson')
        stationInfo.telephone = request.POST.get('stationInfo.telephone')
        stationInfo.postcode = request.POST.get('stationInfo.postcode')
        stationInfo.address = request.POST.get('stationInfo.address')
        stationInfo.save() # 保存机场信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新机场信息
    def get(self, request, stationId):
        context = {'stationId': stationId}
        return render(request, 'StationInfo/stationInfo_modify.html', context)


class ListView(BaseView):  # 后台机场信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'StationInfo/stationInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        stationName = self.getStrParam(request, 'stationName')
        connectPerson = self.getStrParam(request, 'connectPerson')
        telephone = self.getStrParam(request, 'telephone')
        postcode = self.getStrParam(request, 'postcode')
        # 然后条件组合查询过滤
        stationInfos = StationInfo.objects.all()
        if stationName != '':
            stationInfos = stationInfos.filter(stationName__contains=stationName)
        if connectPerson != '':
            stationInfos = stationInfos.filter(connectPerson__contains=connectPerson)
        if telephone != '':
            stationInfos = stationInfos.filter(telephone__contains=telephone)
        if postcode != '':
            stationInfos = stationInfos.filter(postcode__contains=postcode)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(stationInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        stationInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        stationInfoList = []
        for stationInfo in stationInfos_page:
            stationInfo = stationInfo.getJsonObj()
            stationInfoList.append(stationInfo)
        # 构造模板页面需要的参数
        stationInfo_res = {
            'rows': stationInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(stationInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除机场信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        stationIds = self.getStrParam(request, 'stationIds')
        stationIds = stationIds.split(',')
        count = 0
        try:
            for stationId in stationIds:
                StationInfo.objects.get(stationId=stationId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出机场信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        stationName = self.getStrParam(request, 'stationName')
        connectPerson = self.getStrParam(request, 'connectPerson')
        telephone = self.getStrParam(request, 'telephone')
        postcode = self.getStrParam(request, 'postcode')
        # 然后条件组合查询过滤
        stationInfos = StationInfo.objects.all()
        if stationName != '':
            stationInfos = stationInfos.filter(stationName__contains=stationName)
        if connectPerson != '':
            stationInfos = stationInfos.filter(connectPerson__contains=connectPerson)
        if telephone != '':
            stationInfos = stationInfos.filter(telephone__contains=telephone)
        if postcode != '':
            stationInfos = stationInfos.filter(postcode__contains=postcode)
        #将查询结果集转换成列表
        stationInfoList = []
        for stationInfo in stationInfos:
            stationInfo = stationInfo.getJsonObj()
            stationInfoList.append(stationInfo)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(stationInfoList)
        # 设置要导入到excel的列
        columns_map = {
            'stationName': '机场名称',
            'connectPerson': '联系人',
            'telephone': '联系电话',
            'postcode': '邮编',
            'address': '通讯地址',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径

PythonProject/templates/StationInfo/stationInfo_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/stationInfo.css' %}" />
<div id="stationInfoAddDiv">
    {% csrf_token %}
	<form id="stationInfoAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">机场名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="stationInfo_stationName" name="stationInfo.stationName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">联系人:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="stationInfo_connectPerson" name="stationInfo.connectPerson" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">联系电话:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="stationInfo_telephone" name="stationInfo.telephone" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">邮编:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="stationInfo_postcode" name="stationInfo.postcode" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">通讯地址:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="stationInfo_address" name="stationInfo.address" style="width:200px" />

			</span>

		</div>
		<div class="operation">
			<a id="stationInfoAddButton" class="easyui-linkbutton">添加</a>
			<a id="stationInfoClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/StationInfo/stationInfo_add.js' %}"></script>

PythonProject/templates/StationInfo/stationInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>机场信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>机场信息查询</h1>
		</div>
		<form name="stationInfoQueryForm" id="stationInfoQueryForm" action="{% url 'StationInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="stationName">机场名称:</label>
				<input type="text" id="stationName" name="stationName" value="{{ stationName }}" class="form-control" placeholder="请输入机场名称">
			</div>
			<div class="form-group">
				<label for="connectPerson">联系人:</label>
				<input type="text" id="connectPerson" name="connectPerson" value="{{ connectPerson }}" class="form-control" placeholder="请输入联系人">
			</div>
			<div class="form-group">
				<label for="telephone">联系电话:</label>
				<input type="text" id="telephone" name="telephone" value="{{ telephone }}" class="form-control" placeholder="请输入联系电话">
			</div>
			<div class="form-group">
				<label for="postcode">邮编:</label>
				<input type="text" id="postcode" name="postcode" value="{{ postcode }}" class="form-control" placeholder="请输入邮编">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#stationInfoListPanel" aria-controls="stationInfoListPanel" role="tab" data-toggle="tab">机场信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'StationInfo:frontAdd' %}" style="display:none;">添加机场信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="stationInfoListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>机场名称</td><td>联系人</td><td>联系电话</td><td>邮编</td><td>通讯地址</td><td>操作</td></tr>
                                        {% for stationInfo in stationInfos_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ stationInfo.stationName }}</td>
 											<td>{{ stationInfo.connectPerson }}</td>
 											<td>{{ stationInfo.telephone }}</td>
 											<td>{{ stationInfo.postcode }}</td>
 											<td>{{ stationInfo.address }}</td>
 											<td>
 												<a href="{% url 'StationInfo:frontShow' stationInfo.stationId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="stationInfoEdit('{{ stationInfo.stationId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="stationInfoDelete('{{ stationInfo.stationId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="stationInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;机场信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="stationInfoEditForm" id="stationInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="stationInfo_stationId_edit" class="col-md-3 text-right">记录编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="stationInfo_stationId_edit" name="stationInfo.stationId" class="form-control" placeholder="请输入记录编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="stationInfo_stationName_edit" class="col-md-3 text-right">机场名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="stationInfo_stationName_edit" name="stationInfo.stationName" class="form-control" placeholder="请输入机场名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="stationInfo_connectPerson_edit" class="col-md-3 text-right">联系人:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="stationInfo_connectPerson_edit" name="stationInfo.connectPerson" class="form-control" placeholder="请输入联系人">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="stationInfo_telephone_edit" class="col-md-3 text-right">联系电话:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="stationInfo_telephone_edit" name="stationInfo.telephone" class="form-control" placeholder="请输入联系电话">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="stationInfo_postcode_edit" class="col-md-3 text-right">邮编:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="stationInfo_postcode_edit" name="stationInfo.postcode" class="form-control" placeholder="请输入邮编">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="stationInfo_address_edit" class="col-md-3 text-right">通讯地址:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="stationInfo_address_edit" name="stationInfo.address" class="form-control" placeholder="请输入通讯地址">
			 </div>
		  </div>
		</form> 
	    <style>#stationInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxStationInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.stationInfoQueryForm.currentPage.value = currentPage;
    document.stationInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.stationInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.stationInfoQueryForm.currentPage.value = pageValue;
    documentstationInfoQueryForm.submit();
}

/*弹出修改机场信息界面并初始化数据*/
function stationInfoEdit(stationId) {
	$.ajax({
		url :  '/StationInfo/update/' + stationId,
		type : "get",
		dataType: "json",
		success : function (stationInfo, response, status) {
			if (stationInfo) {
				$("#stationInfo_stationId_edit").val(stationInfo.stationId);
				$("#stationInfo_stationName_edit").val(stationInfo.stationName);
				$("#stationInfo_connectPerson_edit").val(stationInfo.connectPerson);
				$("#stationInfo_telephone_edit").val(stationInfo.telephone);
				$("#stationInfo_postcode_edit").val(stationInfo.postcode);
				$("#stationInfo_address_edit").val(stationInfo.address);
				$('#stationInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除机场信息信息*/
function stationInfoDelete(stationId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/StationInfo/deletes",
			data : {
				stationIds : stationId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#stationInfoQueryForm").submit();
					//location.href= basePath + "StationInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交机场信息信息表单给服务器端修改*/
function ajaxStationInfoModify() {
	$.ajax({
		url :   '/StationInfo/update/' + $("#stationInfo_stationId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#stationInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#stationInfoQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
